[dependencies]
  charset = {branch = "v0.0.4.B003", git = "https://gitee.com/HW-PLLab/charset.git", version = "0.0.2"}

[package]
  cjc-version = "0.51.4"
  compile-option = "-O2"
  description = "nothing here"
  link-option = ""
  name = "chardet4cj"
  output-type = "dynamic"
  src-dir = "src"
  target-dir = ""
  version = "0.0.2"
  package-configuration = {}
