[dependencies]
  charset4cj = {branch = "develop", git = "https://gitcode.com/Cangjie-TPC/charset4cj.git", version = "0.0.1"}

[package]
  cjc-version = "0.58.3"
  compile-option = "-O2"
  description = "nothing here"
  link-option = ""
  name = "chardet4cj"
  output-type = "dynamic"
  src-dir = "src"
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}
